---
deployment:
  tasks:
    - export DEPLOYPATH=/home/placerse/public_html/
    - export REPOPATH=/home/placerse/repositories/placerselecto
    - cd $REPOPATH && git fetch --all
    - cd $REPOPATH && git reset --hard origin/main
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -f index.php $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
    - /bin/cp -Rf uploads $DEPLOYPATH 2>/dev/null || true
